apiVersion: v1
kind: Namespace
metadata:
  name: parth-kubes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parth-pvc
  namespace: parth-kubes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: v1
kind: Service
metadata:
  name: container1
  namespace: parth-kubes
spec:
  type: LoadBalancer
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000

---
apiVersion: v1
kind: Service
metadata:
  name: container2
  namespace: parth-kubes
spec:
  type: ClusterIP
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
  namespace: parth-kubes
spec:
  selector:
    matchLabels:
      app: container1
  replicas: 1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: northamerica-northeast1-docker.pkg.dev/csci-5409-cc-418214/container1/parth-container1-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: data-volume
              mountPath: /parth_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: parth-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
  namespace: parth-kubes
spec:
  selector:
    matchLabels:
      app: container2
  replicas: 1
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: northamerica-northeast1-docker.pkg.dev/csci-5409-cc-418214/container2/parth-container2-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data-volume
              mountPath: /parth_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: parth-pvc
